ray stop

# export NCCL_SHM_DISABLE=1 可以生效，但是很慢。
# export NCCL_SHM_DISABLE=1
# NCCL_CUMEM_HOST_ENABLE 也可以生效

# export NCCL_IGNORE_DISABLED_P2P=1
# export NCCL_P2P_DISABLE=1
# export NCCL_CUMEM_HOST_ENABLE=0
export NCCL_CUMEM_HOST_ENABLE=0
# export NCCL_P2P_LEVEL=NVL
# export NCCL_DEBUG=INFO
# export NCCL_DEBUG_SUBSYS=INIT,GRAPH,P2P,SHM
env NCCL_CUMEM_HOST_ENABLE=0 \
    NCCL_DEBUG=INFO \
    NCCL_DEBUG_SUBSYS=INIT,GRAPH,P2P,SHM \
    WANDB_API_KEY=75b560b94c4e949455fa45b3a018987ede3846fa \
    RAY_DEBUG=legacy HYDRA_FULL_ERROR=1 VLLM_USE_V1=1 ray start --head --dashboard-host=0.0.0.0

# env NCCL_IGNORE_DISABLED_P2P=1 \
    # NCCL_P2P_DISABLE=1 \
    # NCCL_CUMEM_HOST_ENABLE=0 \

python train.py
